Try to ensure that the mysql init script doesn't fail when running from dpkg or (... bug?) chef

diff --git a/files/default/mysql.initd b/files/default/mysql.initd
--- a/files/default/mysql.initd
+++ b/files/default/mysql.initd
@@ -63,17 +63,56 @@ MYADMIN="${BINDIR}/mysqladmin --defaults-file=${SYSCONFDIR}/mysql/debian.cnf"
 ERR_LOGGER="logger -p daemon.err -t ${SYSCONFDIR}/init.d/mysql -i"
 
 if ! test -x "${MYSQLD}"; then
-	echo "FATAL: ${MYSQLD} not found"
+	echo >&2 "FATAL: ${MYSQLD} not found"
 	if test x"${1:-}" = x"stop"; then
+		# Arguable, but technically mysql could well be considered stopped if
+		# the binary no longer exists.  Practically, this prevents upgrade
+		# issues where, for some reason, dpkg tries to sto the service *after*
+		# the prior version has been removed.
 		exit 0
 	else
 		exit 1
 	fi
 fi
 
-test -s /lib/lsb/init-functions || { echo "FATAL: /lib/lsb/init-functions does not exist" ; exit 1 ; }
-. /lib/lsb/init-functions || { echo "FATAL: /lib/lsb/init-functions failed to execute" ; exit 1 ; }
+test -s /lib/lsb/init-functions || { echo >&2 "FATAL: /lib/lsb/init-functions does not exist" ; exit 1 ; }
+. /lib/lsb/init-functions || { echo >&2 "FATAL: /lib/lsb/init-functions failed to execute" ; exit 1 ; }
 
+
+function abort() {
+	local -i rc=${1:-1}
+
+	# If we're invoked by dpkg which is itself launched from chef(-solo), then
+	# we actually want to avoid failing under any circumstances, otherwise
+	# we're left with partially-configured packages, which would break even if
+	# chef is instructed to ignore failures...
+	#
+	# FIXME: This code performs an exit(0) if we're running under dpkg OR chef,
+	#        but should we instead be looking for specifically dpkg beneath
+	#        chef?
+	#
+	
+	local stats
+	local -i pid=${$} ppid
+	while true; do
+			(( 1 == pid )) && exit ${rc}
+			[[ -d /proc/${pid} && -s /proc/${pid}/stat ]] || exit ${rc}
+			stats=( $( < /proc/${pid}/stat ) )
+			ppid=${stats[3]}
+			(( 0 == ppid || 1 == ppid )) && exit ${rc}
+			[[ -d /proc/${ppid} && -s /proc/${ppid}/comm ]] || exit ${rc}
+			case "$( < /proc/${ppid}/comm )" in
+				dpkg*|chef|chef-solo)
+					echo >&2 "Running from '$( < /proc/${ppid}/comm )', aborting with result ${rc} => 0"
+					exit 0
+					;;
+			esac
+			pid=${ppid}
+	done
+
+	# Unreachable
+	exit 1
+} # abort
 
 function log_warning() {
 	local message="${@}"
@@ -237,7 +276,7 @@ function main() {
 		'start')
 			local -i timeout=${MYSQLD_STARTUP_TIMEOUT:-120}
 
-			sanity_checks || exit 1
+			sanity_checks || return 1
 
 			# Start daemon
 			#
@@ -457,7 +496,7 @@ function main() {
 				log_end_msg 1
 				log_failure_msg "Please stop MariaDB manually and read" \
 					"/usr/share/doc/mariadb-server-5.5/README.Debian.gz!"
-				exit 1
+				return 1
 			else
 				log_end_msg 0
 			fi
@@ -486,13 +525,13 @@ function main() {
 				log_action_msg "$( ${MYADMIN} version )"
 			else
 				log_action_msg "MariaDB is stopped."
-				exit 3
+				return 3
 			fi
 			;;
 
 		*)
 			echo "Usage: $SELF start|stop|restart|reload|force-reload|status"
-			exit 1
+			return 1
 			;;
 	esac
 
@@ -501,6 +540,6 @@ function main() {
 
 main "${@:-}"
 
-exit ${?}
+abort ${?}
 
 # vi: set ts=4:
