Add additional replication tunables, fix init script for non-clustered usage

diff --git a/files/default/mysql.initd b/files/default/mysql.initd
--- a/files/default/mysql.initd
+++ b/files/default/mysql.initd
@@ -20,22 +20,29 @@
 
 # Exit immediately if pipeline element, sub-shell command, or braced-section
 # returns 1...
+#
 #set -e
 
 # Abort on unbound variable usage...
+#
 set -u
 
 # Impose sane pipe-handing
+#
 set -o pipefail
 
 if [[ -n "${DEBIAN_SCRIPT_DEBUG:-}" ]]; then
 	# Print input lines as they are read...
+	#
 	set -v
 	# Show the results of all command-expansions...
+	#
 	set -x
 fi
 
-SPACENEEDED="$(( 50 << 10 ))" # 50MiB of 1KiB blocks...
+# 50MiB of 1KiB blocks...
+#
+SPACENEEDED="$(( 50 << 10 ))"
 
 PREFIX='/usr'
 EPREFIX="${PREFIX:-/usr}"
@@ -52,6 +59,7 @@ MYSQLD="${SBINDIR}"/mysqld
 MYADMIN="${BINDIR}/mysqladmin --defaults-file=${SYSCONFDIR}/mysql/debian.cnf"
 
 # Priority can be overriden; '-s' adds output to stderr
+#
 ERR_LOGGER="logger -p daemon.err -t ${SYSCONFDIR}/init.d/mysql -i"
 
 if ! test -x "${MYSQLD}"; then
@@ -108,9 +116,10 @@ function bytestohr() {
 	echo "${val}$( echo "${slist}" | cut -f${power} -d, )"
 }
 
-# mysqladmin likes to read /root/.my.cnf. This is usually not what I want
-# as many admins e.g. only store a password without a username there and
-# so break my scripts.
+# mysqladmin likes to read /root/.my.cnf. This is usually not what is wanted
+# as this file may contain, for example, a password without a username and so
+# could break scripts ...
+#
 export HOME="${SYSCONFDIR}"/mysql
 
 ## Fetch a particular option from mysql's invocation.
@@ -133,10 +142,12 @@ mysqld_get_param() {
 #
 sanity_checks() {
 	# Check for config file
+	#
 	[[ -r "${CONF}" ]] || \
 		log_warning "${CONF} cannot be read. See 'README.Debian.gz'"
 
-	# Check for diskspace shortage
+	# Fielsystem space check ...
+	#
 	local datadir="$( mysqld_get_param datadir )"
 
 	if ! [[ -d "${datadir}" ]]; then
@@ -160,22 +171,16 @@ sanity_checks() {
 	return 0
 } # sanity_checks
 
-## Checks if there is a server running and if so whether it is accessible.
+## Check if there is a server running and, if so, whether it is accessible.
 #
 # Usage: boolean mysqld_status [check_alive|check_dead] [warn|nowarn]
-#  check_alive insists on a pingable server
-#  check_dead also fails if there is a lost mysqld in the process list
+#  'check_alive' insists on a server which responds to ping/ICMP echo-request;
+#  'check_dead' also fails if there is an orphaned mysqld in the process list.
 #
 mysqld_status () {
 	local pidfile="$( mysqld_get_param pid-file 2>/dev/null )"
 	local user="$( mysqld_get_param user 2>/dev/null )"
 	local args
-
-	#if [[ -s "${pidfile}" ]] \
-	#	&& ps "$( cat "${pidfile}" )" >/dev/null 2>&1
-	#then
-	#	ps_alive=1
-	#fi
 
 	if [[ -n "${DEBIAN_SCRIPT_DEBUG:-}" ]]; then
 		args="--verbose"
@@ -189,6 +194,7 @@ mysqld_status () {
 	local -i ps_alive=$(( !( ${?} ) ))
 
 	# bash always returns '0' if the following two lines are conjoined...
+	#
 	local ping_output
 	ping_output="$( ${MYADMIN} ping 2>&1 )"
 	local -i ping_alive=$(( !( ${?} ) ))
@@ -197,11 +203,13 @@ mysqld_status () {
 		&& (( ping_alive ))
 	then
 		# EXIT_SUCCESS
+		#
 		return 0
 	elif [[ "${1}" == "check_dead" ]] \
 		&& (( !( ping_alive || ps_alive ) ))
 	then
 		# EXIT_SUCCESS
+		#
 		return 0
 	else
 		if [[ "${2}" == "warn" ]]; then
@@ -210,15 +218,15 @@ mysqld_status () {
 				"${ping_output}" \
 			| ${ERR_LOGGER} -p daemon.debug
 		fi
+
 		# EXIT_FAILURE
+		#
 		return 1
 	fi
 } # mysqld_status
 
+## Main loop
 #
-# main()
-#
-
 function main() {
 	local option="${1:-}" ; shift
 
@@ -232,6 +240,7 @@ function main() {
 			sanity_checks || exit 1
 
 			# Start daemon
+			#
 			log_daemon_msg "Starting MariaDB database server" "mysqld"
 
 			if mysqld_status check_alive nowarn; then
@@ -243,7 +252,8 @@ function main() {
 				local args
 				local -i i
 
-				# Could be removed during boot
+				# Could be removed during boot?
+				#
 				test -e "${LOCALSTATEDIR}"/run/mysqld \
 					|| install \
 						-m 755 \
@@ -252,6 +262,7 @@ function main() {
 						-d "${LOCALSTATEDIR}"/run/mysqld
 
 				# Remove stale PID files
+				#
 				[[ -e "${pidfile}" ]] && rm -f "${pidfile}" >/dev/null 2>&1
 
 				if [[ -n "${DEBIAN_SCRIPT_DEBUG:-}" ]]; then
@@ -269,6 +280,7 @@ function main() {
 				fi
 
 				# Load AppArmor profile
+				#
 				if type -pf aa-status >/dev/null 2>&1; then
 					if aa-status --enabled 2>/dev/null; then
 						apparmor_parser \
@@ -279,12 +291,8 @@ function main() {
 						/lib/init/apparmor-profile-load usr.sbin.mysqld
 				fi
 
-				## Start MariaDB!
-				#if [[ -n "${DEBIAN_SCRIPT_DEBUG:-}" ]]; then
-				#	"${BINDIR}"/mysqld_safe "${@:2}" &
-				#else
-				#	"${BINDIR}"/mysqld_safe "${@:2}" >/dev/null 2>&1 &
-				#fi
+				# Start MariaDB
+				#
 				start-stop-daemon                             \
 					${pidfile:+--pidfile "${pidfile}"}    \
 					--exec "${BINDIR}"/mysqld_safe        \
@@ -306,8 +314,9 @@ function main() {
 					fi
 				fi
 
-				# 6s was reported in #352070 to be too few when using
-				# ndbcluster
+				# 6 seconds was reported in Bug #352070 to be too small an
+				# amount of time when using ndbcluster ...
+				#
 				(( timeout )) || timeout=120
 				local -i statustimeout=${timeout}
 				if (( 1 != multiplier )); then
@@ -324,7 +333,19 @@ function main() {
 					fi
 					(( i % multiplier )) || log_progress_msg "."
 				done
-				if mysqld_status check_alive warn; then
+				if ! mysqld_status check_alive warn; then
+					log_end_msg 1
+					log_failure_msg "Please see syslog for details"
+					return 1
+				fi
+
+				if ! [[ -r /etc/mysql/conf.d/galera.cnf ]]; then
+					log_action_msg "If this instance is a new replication slave, then it needs to be initialised by"
+					log_action_msg "loading a database backup from a known co-ordinate, and then executing:"
+					log_action_msg "  CHANGE MASTER TO master_host='<master>', master_user='repl',"
+					log_action_msg "      master_password='<password>', master_log_file='<log>',"
+					log_action_msg "      master_log_pos=<co-ordinate>;"
+				else
 					local dbuser="root"
 					local dbhost="localhost"
 					local grants="/etc/mysql_grants.sql"
@@ -363,7 +384,6 @@ function main() {
 										log_progress_msg "mysqld cluster status is '${val:-}' - waiting for initialisation ..."
 										sleep 1
 									fi
-
 								done < <( mysql -u "${dbuser}" -p"${rootpw}" -h "${dbhost}" mysql <<<"SHOW STATUS LIKE 'wsrep_ready'" | tail -n +2 | head -n 1 )
 							done
 						fi
@@ -372,29 +392,31 @@ function main() {
 
 					if (( 1 != finished )); then
 						log_failure_msg "Galera cluster failed to synchronise"
-					else
-						# Run site-local post-up script...
-						local output="$(
-							"${SYSCONFDIR}"/mysql/debian-start
-						)"
-						[[ -n "${output}" ]] && \
-							log_action_msg "${output}"
+						return 1
 					fi
-				else
-					log_end_msg 1
-					log_failure_msg "Please see syslog for details"
+				fi # ! [[ -r /etc/mysql/conf.d/galera.cnf ]]
+
+				if [[ -r "${SYSCONFDIR}"/mysql/debian-start ]]; then
+					# Run site-local post-up script...
+					#
+					local output="$(
+						"${SYSCONFDIR}"/mysql/debian-start
+					)"
+					[[ -n "${output}" ]] && \
+						log_action_msg "${output}"
 				fi
-			fi
+			fi # ! mysqld_status check_alive nowarn
 			;;
 
 		'stop')
 			local -i timeout=${MYSQLD_SHUTDOWN_TIMEOUT:-600}
 			local -i r
 
-			# * As a passwordless mysqladmin (e.g. via ~/.my.cnf) must be possible
-			# at least for cron, we can rely on it here, too. (although we have
-			# to specify it explicit as e.g. sudo environments points to the normal
-			# users home and not /root)
+			# " * As a passwordless mysqladmin (e.g. via ~/.my.cnf) must be possible
+			#   at least for cron, we can rely on it here, too. (although we have
+			#   to specify it explicit as e.g. sudo environments points to the normal
+			#   users home and not /root)
+			# "
 			#
 			# ^^^ WTF?? ^^^
 
@@ -408,24 +430,11 @@ function main() {
 				output="$( ${MYADMIN} shutdown 2>&1 )"
 				r=${?}
 				#set -e
+
 				if (( r )); then
 					log_end_msg 1
 					[[ "${VERBOSE}" != "no" ]] && \
 						log_failure_msg "Error: ${output}"
-					#log_daemon_msg "Killing MariaDB database" \
-					#	"server by signal" "mysqld"
-					#killall -15 mysqld
-					#server_down=
-					#for i in `seq 1 600`; do
-					#	sleep 1
-					#	if mysqld_status check_dead nowarn; then
-					#		server_down=1
-					#		break
-					#	fi
-					#done
-					#if test -z "$server_down"; then
-					#	killall -9 mysqld
-					#fi
 					log_daemon_msg "'${MYADMIN}' failed to stop" \
 						"mysqld: stopping with start-stop-daemon"
 
@@ -457,9 +466,12 @@ function main() {
 		'restart')
 			# Exit immediately if pipeline element, sub-shell command, or braced-section
 			# returns 1...
+			#
+
 			#set +e
 			"${SELF}" stop
 			#set -e
+
 			"${SELF}" start "${@:-}"
 			;;
 
